import NextHead from 'next/head'

export function Head() {
  return (
    <NextHead>
      <title>MyEcommerce</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.png" />
    </NextHead>
  )
}
